### ISSUE TITLE
WebpackError: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by opeah** [react-spring/react-use-measure#4]
Thanks for the useful tool! 👍 

Got an error with Gatsby :

react-use-measure 1.1.2
gatsby 2.16.5

<img width="964" alt="Capture d’écran 2019-11-06 à 10 06 53" src="https://user-images.githubusercontent.com/31569566/68284228-61cda300-007d-11ea-8058-58c7852f126c.png">

**Comment by drcmda** [comment]
do you know how to avoid it? i have never used ssr/gatsby/zeit before. i can do something like this:

```jsx
const isomorphicWindow = typeof window !== 'undefined' ? window : ({} as any)
const ResizeObserver = isomorphicWindow.ResizeObserver || Polyfill
```

but the code is otherwise using window a lot, window.addventListener, window.getComputedStyle, etc. is it ok if it happens in the hooks or will gatsby call them and crash again?

**Comment by everweij** [comment]
Thanks @opeah! I've run into this 'window' issue in the past, and yes Paul, your solution is correct. As far as I understand it, React ignores code in `useEffect`, so in our case we only have to focus on the ResizeObserver polyfill. I've added a separate test that covers ssr. Seems to work fine now :)

**Comment by opeah** [comment]
Thanks both for the quick fix :)
